# Generated by Django 4.2.30 on 2026-08-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
