# Generated by Django 4.2.30 on 2026-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_poscategory_poscustomer_posproduct_possale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poscategory',
            name='mode',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('club', 'Club'), ('supermarket', 'Supermarket'), ('coffeeshop', 'Coffee Shop'), ('cafe', 'Cafe')], default='restaurant', max_length=20),
        ),
    ]
