# Generated by Django 4.2.30 on 2026-08-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_poscategory_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='posproduct',
            name='image',
            field=models.URLField(blank=True, help_text='URL to product image', max_length=500),
        ),
    ]
