# Generated by Django 6.1 on 2026-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_posproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('whatsapp', 'WhatsApp Order')], default='whatsapp', max_length=20),
        ),
    ]
