# Generated by Django 6.1 on 2026-08-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='External image URL for products', max_length=500),
        ),
    ]
