# Generated by Django 6.1 on 2026-08-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_external_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software License')], default='hardware', max_length=10),
        ),
    ]
