# Generated by Django 5.0.6 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_quote_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, help_text="Your unit purchase cost. Used for profit and loss reporting.", max_digits=12),
        ),
    ]
