# Generated by Django 5.0.6 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_cost_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processed", "Processed"),
                    ("completed", "Completed"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
    ]
