# Generated by Django 5.0.6 on 2026-09-19 12:13

import catalog.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_update_quote_contact_email'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ShopPromo',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('tag', models.CharField(default='Deal', help_text='Small pill label, e.g. HOT DEAL', max_length=40)),
        #         ('title', models.CharField(max_length=120)),
        #         ('subtitle', models.CharField(blank=True, max_length=160)),
        #         ('href', models.CharField(help_text='e.g. ?q=laptop, ?type=hardware or a full URL', max_length=300, verbose_name='Link URL')),
        #         ('image', models.CharField(help_text='Static path like /static/images/promos/promo_laptop_deals.png, or any full image URL', max_length=400, verbose_name='Image path')),
        #         ('kind', models.CharField(choices=[('feature', 'Featured banner (wide)'), ('card', 'Promo card (small)')], default='card', max_length=10)),
        #         ('order', models.PositiveIntegerField(default=0)),
        #         ('is_active', models.BooleanField(default=True)),
        #     ],
        #     options={
        #         'verbose_name': 'Shop advert',
        #         'verbose_name_plural': 'Shop adverts',
        #         'ordering': ['order', 'id'],
        #     },
        # ),
        migrations.CreateModel(
            name='ReportCenter',
            fields=[
            ],
            options={
                'verbose_name': 'Reports',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.AlterField(
            model_name='quote',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='quote',
            name='valid_until',
            field=models.DateField(default=catalog.models.default_quote_valid_until),
        ),
        migrations.AlterField(
            model_name='quotesettings',
            name='payment_details',
            field=models.TextField(blank=True, default='Payment is due before delivery or installation.'),
        ),
        migrations.AlterField(
            model_name='quotesettings',
            name='terms',
            field=models.TextField(blank=True, default='1. Payment: 100% before Dispatch.\n2. Price Validity: Prices are valid for 14 days from the quotation date.\n3. Delivery: On receipt of LPO / PAYMENT.\n4. Warranty: One (1) Year Warranty where applicable from the date of installation.\n5. The equipment should be plugged into a clean power source (UPS and adequate Earthing).\n6. All goods remain the property of Jabem Solutions Limited until payment is received in full. Lipa Na Mpesa Paybill No-247247 Account Number: 309061 or Paybill-516600 Account Number: 309061. Business Name: Jabem Solutions Limited.\n\nFor Clarifications, please contact Jabem Solutions Limited, +254736 794 594, info@jabemsolutions.co.ke.\nIMPORTANT - When making a payment, kindly pay against the Account above.'),
        ),
    ]
