# Generated by Django 5.0.6 on 2026-09-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_shoppromo_reportcenter_product_shop_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_slot',
            field=models.CharField(blank=True, choices=[('', '— Not in a shop section —'), ('new_arrival', 'New Arrivals')], default='', help_text='Show this product in a themed section on the shop page.', max_length=12, verbose_name='Shop section'),
        ),
    ]
